// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsfZPqtc5hTQYXsDcK98CJ6C_NHX4bsIM',
    appId: '1:134731359495:web:570f9978c1d6bdf82891a2',
    messagingSenderId: '134731359495',
    projectId: 'dimaproject-407114',
    authDomain: 'dimaproject-407114.firebaseapp.com',
    storageBucket: 'dimaproject-407114.appspot.com',
    measurementId: 'G-LC3QDMC0BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9De6Bdey6uJcjca5uJfRsvv-GtGbw9wk',
    appId: '1:134731359495:android:d02ed0dfde47d1b92891a2',
    messagingSenderId: '134731359495',
    projectId: 'dimaproject-407114',
    storageBucket: 'dimaproject-407114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDZnR8LFfPUx25A4Dw5BMODbGNHqyMUo8',
    appId: '1:134731359495:ios:1705d8c915aece912891a2',
    messagingSenderId: '134731359495',
    projectId: 'dimaproject-407114',
    storageBucket: 'dimaproject-407114.appspot.com',
    iosBundleId: 'com.example.dimaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDZnR8LFfPUx25A4Dw5BMODbGNHqyMUo8',
    appId: '1:134731359495:ios:95c5582132034b022891a2',
    messagingSenderId: '134731359495',
    projectId: 'dimaproject-407114',
    storageBucket: 'dimaproject-407114.appspot.com',
    iosBundleId: 'com.example.dimaProject.RunnerTests',
  );
}
